let data = [
  {
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "프리랜서 개발팀을 찾습니다!",
    target: ["전체"],
    stack: ["js", "react", "ts", "vue"],
    writer: "디온",
    comments: "저 참여 희망합니다 연락주세요",
  },

  {
    tag: ["project", "new"],
    end: "2023.09.08",
    title: "[사이드프로젝트] 대학교 미팅 어플을 위해 디자이너님을 모집합니다.",
    target: ["디자이너", "프론트엔드"],
    stack: ["vue", "next"],
    writer: "다다",
  },

  {
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[사프, FE모집] 케이크 정보 제공 및 예약 서비스(New)",
    target: ["디자이너", "프론트엔드"],
    stack: ["js"],
    writer: "디온",
    comments: ["저 참여 희망합니다 연락주세요", "여기 프로젝트 맛집이네요."],
  },
  {
    id: 3,
    tag: ["project", "hot"],
    end: "2023.10.31",
    title: "[IT 서비스 크루] 기깔나는 사람들에서 크루원을 모집합니다",
    target: ["백엔드", "프론트엔드"],
    stack: ["js", "next"],
    writer: "디온",
  },
  {
    id: 4,
    tag: ["study", "new"],
    end: "2023.10.31",
    title: "사이드 프로젝트(앱) 같이 하실 프론트 개발자분 한분 모십니다",
    target: ["프론트엔드", "IOS"],
    stack: ["js", "vue"],
    writer: "바룸",
    comments: [
      "저 참여 희망합니다 연락주세요",
      "여기 프로젝트 맛집이네요.",
      "마감됐습니까?",
    ],
  },
  {
    id: 5,
    tag: ["project", "hot"],
    end: "2023.10.31",
    title: "[IT 서비스 크루] 기깔나는 사람들에서 크루원을 모집합니다",
    target: ["디자이너"],
    stack: ["js", "react", "vue"],
    writer: "디온",
  },
  {
    id: 6,
    tag: ["study", "new"],
    end: "2023.10.31",
    title:
      "[사이드 프로젝트] 예약결제 플랫폼 개발 프로젝트 팀원 추가모집 합니다:)",
    target: ["백엔드"],
    stack: ["js", "ts"],
    writer: "바룸",
    comments: [
      "저 참여 희망합니다 연락주세요",
      "여기 프로젝트 맛집이네요.",
      "마감됐습니까?",
    ],
  },
  {
    id: 7,
    tag: ["new"],
    end: "2023.10.31",
    title:
      "[사이드 프로젝트] 예약결제 플랫폼 개발 프로젝트 팀원 추가모집 합니다:)",
    target: ["백엔드"],
    stack: ["js", "ts"],
    writer: "바룸",
  },
  {
    id: 8,
    tag: ["new"],
    end: "2023.10.31",
    title: "아자르 같이 화상채팅을 활용한 앱 서비스",
    target: ["프론트엔드"],
    stack: ["js", "ts", "react"],
    writer: "바룸",
    comments: [
      "저 참여 희망합니다 연락주세요",
      "여기 프로젝트 맛집이네요.",
      "마감됐습니까?",
    ],
  },
  {
    id: 9,
    tag: ["project"],
    end: "2023.10.31",
    title: "[IT 서비스 크루] 기깔나는 사람들에서 크루원을 모집합니다!",
    target: ["프론트엔드"],
    stack: ["ts", "react"],
    writer: "kuice",
  },
  {
    id: 10,
    tag: ["project", "hot"],
    end: "2023.10.31",
    title: "[IT 서비스 크루] 기깔나는 사람들에서 크루원을 모집합니다!",
    target: ["프론트엔드"],
    stack: ["ts", "react", "figma"],
    writer: "기티",
  },
];

export default data;
