let data = [
  {
    id: 0,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "프리랜서 개발팀을 찾습니다!",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",
    target: ["전체"],
    stack: ["JavaScript", "React", "Typescript", "Vue"],
    writer: "디온",
    comments: [
      {
        commentAuthor: "냐냐",
        commentCon: "저 참여 희망합니다 연락주세요",
        date: "2023-08-28 11:52:55",
      },
    ],
  },

  {
    id: 1,
    tag: ["project", "new"],
    end: "2023.09.08",
    title: "[사이드프로젝트] 대학교 미팅 어플을 위해 디자이너님을 모집합니다.",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    target: ["디자이너", "프론트엔드"],
    stack: ["Vue", "next"],
    writer: "다다",
  },

  {
    id: 2,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[사프, FE모집] 케이크 정보 제공 및 예약 서비스(New)",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    target: ["디자이너", "프론트엔드"],
    stack: ["JavaScript"],
    writer: "디온",
    comments: [
      {
        commentAuthor: "냐냐",
        commentCon: "저 참여 희망합니다 연락주세요",
        date: "2023-08-28 11:52:55",
      },
      {
        commentAuthor: "냐냐",
        commentCon: "여기 프로젝트 맛집이네요.",
        date: "2023-08-28 11:52:55",
      },
    ],
  },
  {
    id: 3,
    tag: ["project", "hot"],
    end: "2023.10.31",
    title: "[IT 서비스 크루] 기깔나는 사람들에서 크루원을 모집합니다",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    target: ["백엔드", "프론트엔드"],
    stack: ["JavaScript", "next"],
    writer: "디온",
  },
  {
    id: 4,
    tag: ["study", "new"],
    end: "2023.10.31",
    title: "사이드 프로젝트(앱) 같이 하실 프론트 개발자분 한분 모십니다",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    target: ["프론트엔드", "IOS"],
    stack: ["JavaScript", "Vue"],
    writer: "바룸",
    comments: [
      {
        commentAuthor: "냐냐",
        commentCon: "저 참여 희망합니다 연락주세요",
        date: "2023-08-28 11:52:55",
      },
      {
        commentAuthor: "니니",
        commentCon: "여기 프로젝트 맛집이네요.",
        date: "2023-08-28 11:52:55",
      },
      {
        commentAuthor: "뇨뇨",
        commentCon: "마감됐습니까?",
        date: "2023-08-28 11:52:55",
      },
    ],
  },
  {
    id: 5,
    tag: ["project", "hot"],
    end: "2023.10.31",
    title: "[IT 서비스 크루] 기깔나는 사람들에서 크루원을 모집합니다",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    target: ["디자이너"],
    stack: ["JavaScript", "React", "Vue"],
    writer: "디온",
  },
  {
    id: 6,
    tag: ["study", "new"],
    end: "2023.10.31",
    title:
      "[사이드 프로젝트] 예약결제 플랫폼 개발 프로젝트 팀원 추가모집 합니다:)",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    target: ["백엔드"],
    stack: ["JavaScript", "Typescript"],
    writer: "바룸",
    comments: [
      {
        commentAuthor: "냐냐",
        commentCon: "저 참여 희망합니다 연락주세요",
        date: "2023-08-28 11:52:55",
      },
      {
        commentAuthor: "니니",
        commentCon: "여기 프로젝트 맛집이네요.",
        date: "2023-08-28 11:52:55",
      },
      {
        commentAuthor: "뇨뇨",
        commentCon: "마감됐습니까?",
        date: "2023-08-28 11:52:55",
      },
    ],
  },
  {
    id: 7,
    tag: ["study", "new"],
    end: "2023.10.31",
    title:
      "[사이드 프로젝트] 예약결제 플랫폼 개발 프로젝트 팀원 추가모집 합니다:)",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    target: ["백엔드"],
    stack: ["JavaScript", "Typescript"],
    writer: "바룸",
  },
  {
    id: 8,
    tag: ["study", "new"],
    end: "2023.10.31",
    title: "아자르 같이 화상채팅을 활용한 앱 서비스",
    target: ["프론트엔드"],
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    stack: ["JavaScript", "Typescript", "React"],
    writer: "바룸",
    comments: [
      {
        commentAuthor: "냐냐",
        commentCon: "저 참여 희망합니다 연락주세요",
        date: "2023-08-28 11:52:55",
      },
      {
        commentAuthor: "니니",
        commentCon: "여기 프로젝트 맛집이네요.",
        date: "2023-08-28 11:52:55",
      },
      {
        commentAuthor: "뇨뇨",
        commentCon: "마감됐습니까?",
        date: "2023-08-28 11:52:55",
      },
    ],
  },
  {
    id: 9,
    tag: ["project"],
    end: "2023.10.31",
    title: "[IT 서비스 크루] 기깔나는 사람들에서 크루원을 모집합니다!",
    content:
      "프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다. 프로젝트 소개가 들어갑니다.  안녕하세요 ! AI 반려동물 온라인 스튜디오, “Purry”를 만들고 있는 포징(Pawsing) 팀입니다. 팀이 만들어진지 10개월만에 누적 지원금 약 8000만원의 성과를 달성하는 등, 정말 빠르게 성장하고 있어요!",

    target: ["프론트엔드"],
    stack: ["Typescript", "React"],
    writer: "kuice",
  },
  {
    id: 10,
    tag: ["project", "hot"],
    end: "2023.10.31",
    title: "[IT 서비스 크루] 기깔나는 사람들에서 크루원을 모집합니다!",
    target: ["프론트엔드", "IOS", "디자이너"],
    stack: ["Typescript", "React", "figma"],
    writer: "기티",
  },
  {
    id: 11,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "(부산) 김영한의 스프링 완전 정복 로드맵과 함께 스터디진행 하실 분",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring", "Nodejs"],
    writer: "심",
  },
  {
    id: 12,
    tag: ["project", "study"],
    end: "2023.10.31",
    title: "(부산) 김영한의 스프링 완전 정복 로드맵과 함께 스터디진행 하실 분",
    target: ["백엔드"],
    stack: ["Java", "Spring", "Nodejs"],
    writer: "심tla",
  },
  {
    id: 13,
    tag: ["project", "study"],
    end: "2023.10.31",
    title: "(부산) 김영한의 스프링 완전 정복 로드맵과 함께 스터디진행 하실 분",
    target: ["백엔드"],
    stack: ["Java"],
    writer: "사사",
  },
  {
    id: 14,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "백엔드 모집) 콘텐츠 서비스'작가의 정원' 사이드프로젝트",
    target: ["백엔드"],
    stack: ["Java", "Spring", "Nodejs"],
    writer: "심",
  },
  {
    id: 15,
    tag: ["project", "hot"],
    end: "2023.10.31",
    title: "백엔드 모집) 콘텐츠 서비스'작가의 정원' 사이드프로젝트",
    target: ["백엔드", "프론트엔드"],
    stack: ["Go", "Kotlin", "Express"],
    writer: "야호",
  },
  {
    id: 16,
    tag: ["new", "project"],
    end: "2023.10.31",
    title: "(부산) 김영한의 스프링 완전 정복 로드맵과 함께 스터디진행 하실 분",
    target: ["백엔드"],
    stack: ["Java", "Spring"],
    writer: "심",
  },
  {
    id: 17,
    tag: ["hot", "study"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "프론트엔드"],
    stack: ["Java", "Spring"],
    writer: "disid",
  },
  {
    id: 18,
    tag: ["study", "new"],
    end: "2023.10.31",
    title: "(부산) 김영한의 스프링 완전 정복 로드맵과 함께 스터디진행 하실 분",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "vod",
  },
  {
    id: 19,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 20,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 21,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 22,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 23,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 24,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 25,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 26,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 27,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 28,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 29,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 30,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 31,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 32,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 33,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 34,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 35,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 36,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 37,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 38,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 39,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 40,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 41,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 42,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 43,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 44,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 45,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 46,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 47,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 48,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 49,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 50,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 51,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 52,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 53,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 54,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 55,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 56,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 57,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 58,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
  {
    id: 59,
    tag: ["project", "new"],
    end: "2023.10.31",
    title: "[설명회] 사이드 프로젝트로 창업하기",
    target: ["백엔드", "IOS"],
    stack: ["Java", "Spring"],
    writer: "니아니아냐냐",
  },
];

export default data;
